#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh does
#       not find so, but you have some other shells available, you may want to
#       execute the script with one of these shells instead.
#       * ash
#       * bash
#       * ksh
#       * mksh
#       * pdksh
#       Try to use a shell if the exec fails.
#
#   (2) Now that issue #825 (separating products) is addressed, following will
#       be used to determine if wheel is needed:
#           a) GRADLE_OPTS environment variable is set, OR
#           b) ".gradletasknamecache" file exists in the parent directories.
#
#       If wheel is needed, a directory ".gradle" will be created under the
#       first directory in the path containing user.home.
#
#       Otherwise, this script will fail with an error message to stderr.
#
##############################################################################

set -e

APP_NAME="Gradle"
APP_BASE_NAME=$(basename "$0")

# Add default JVM options here. You can also use JAVA_OPTS and GRADLE_OPTS to pass JVM options to this script.
DEFAULT_JVM_OPTS='"-Xmx64m" "-Xms64m"'

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD="maximum"

warn() {
    echo "$*" >&2
}

die() {
    echo
    echo "$*"
    echo
    exit 1
}

# OS specific support (must be 'true' or 'false').
darwin=false
msys=false
cygwin=false
nativewin=false
case "$(uname)" in
  Darwin* )
    darwin=true
    ;;
  MINGW* )
    msys=true
    ;;
  CYGWIN* )
    cygwin=true
    ;;
  MSYS* )
    nativewin=true
    ;;
esac

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nativewin" ; then
    case $( ulimit -S -n ) in #(
      'unlimited'|2[0-9][0-9][0-9][0-9][0-9][0-9]|1[0-9][0-9][0-9][0-9][0-9][0-9][0-9]|2[0-9][0-9][0-9][0-9][0-9][0-9]|1[0-9][0-9][0-9][0-9][0-9][0-9]|[1-9][0-9][0-9][0-9][0-9][0-9]|[1-9][0-9][0-9][0-9][0-9]|[1-9][0-9][0-9][0-9]) ;;
      *) # If we get here, ulimit -S -n is not > 3.
        if [ -f /etc/profile.d/bash_completion.sh ] ; then
            . /etc/profile.d/bash_completion.sh
        fi
        ulimit -S -n 262144
        ;;
    esac
fi

# Collect all arguments for the java command, and put them in the array
# before the "CMD".
#   * "$@" stops at first "not an option", which is usually the "CMD".
#   * The args are quoted via eval to preserve contained spaces.
#   * eval 'for arg in "$@"; do printf '%s\n' "$arg"; done' to see the quoting clearly.
#   * Not needed in zsh, where "$@" splitting + globbing is disabled by default.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" output processing is terminated by one of these signals.
if ! is_msys_wsl ; then
    trap 'die' TERM INT
fi

# Use "xargs" to parse quoted args.
# With -n1 it outputs one arg per line, when -0 it uses NUL character to delimit.
# The -I {} makes "xargs" to use the replacement string "{}" instead of adding
# the arguments at the end of the command line.
#   i.e., "xargs -I {} sh -c 'do_something \"{}\"' \
#   where do_something() { echo "Doing $1"; }

find_java_exec() {
    if [ -x /usr/libexec/java_home ]; then
        JAVA_HOME=$( /usr/libexec/java_home )
    else
        JAVA_HOME=$( dirname "$JAVA" )
    fi
}

has_space() {
	case "$1" in
	  *\ * )
	    true ;;
	  *)
	    false ;;
	esac
}

quote_args() {
    local arg
    for arg do
        has_space "$arg" && arg="\"$arg\""
        printf '%s\n' "$arg"
    done
}

APP_ARGS=$( quote_args "$@" )

exec "${JAVACMD}" "${JVM_OPTS[@]}" -classpath "$CLASSPATH" org.gradle.wrapper.GradleWrapperMain "$APP_ARGS"
